---
output:
  distill::distill_article
editor_options: 
  markdown: 
    wrap: 50
geometry: margin=0.75in
fontsize: 11pt
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
---

# **MATTHEW FERRIS**


### **EDUCATION**

**Master of Professional Accountancy, Minor in Accounting Data
Analytics**\
Adkerson School of Accountancy, Mississippi State University,
Starkville, Mississippi. May 2022.

**Bachelor of Accountancy, Minors in Business Analytics and German**\
Adkerson School of Accountancy, Mississippi State University,
Starkville, Mississippi. May 2021.


### **EXPERIENCE**

**Graduate Assistant,** May 2021 - Current\
Bagley College of Engineering, Starkville, Mississippi.\
- Maintain undergraduate student records for the Mechanical Engineering
students and related databases.\
- Advise students, with attention given to select an academic schedule,
major selection, and graduation progress.

**Intern,** December 2019 - May 2021\
University Christian Student Center (UCSC), Starkville, Mississippi.\
- Taught Bible classes to an audience of forty to sixty people.\
- Assisted in the development of educational, leadership, service, and
social programs to enrich the spiritual and mental lives of the college
students.\
- Assisted the Campus Minister in public relations activities, such as
recruit incoming students, develop newsletters, and maintain alumni list
and contacts.

**Financial Management Intern,** May 2020 - August 2020\
Federal Deposit Insurance Corporation (FDIC), Jackson, Mississippi.\
- Assisted in the safety and soundness examinations of banking
institutions.\
- Analyzed and compared bank data for misrepresentations, suspicious
activity, and compliance with regulations.\
- Prepared written examination comments regarding CAMELS ratings per
FDIC regulations and guidelines.\
- Communicated effectively in a virtual environment with examination
team members.\

### **ACTIVITIES AND HONORS** \ 
-   American Institute for Certified Public Accountants, Student
    Affiliate, September 2018 - Present
-   Habitat for Humanity Campus Chapter, August 2018 - Present
    -   Treasurer, August 2018 - August 2019 
    -   President, August 2019 - August 2020
-   German Club, August 2018 - Present
-   Starkville church of Christ, August 2017 - Present 
    -   Service Ministry Representative, August 2019 - December 2019\
    

### **SKILLS**
* Proficient in Microsoft Office Suite (Word, Excel,
Access, and PowerPoint)\
* Proficient in the R programming language and the
Structured Query Language (SQL)

\pagenumbering{gobble}

